[package]
name = "battery_control"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
bare_err_tree.workspace = true
ctrlc.workspace = true
gpio-cdev.workspace = true
i2cdev.workspace = true
log.workspace = true
sd-notify.workspace = true
spidev.workspace = true
spin_sleep.workspace = true
systemd-journal-logger.workspace = true
thiserror.workspace = true
