[package]
name = "keyboard"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
gpio-cdev.workspace = true
nix.workspace = true
spin_sleep.workspace = true
log.workspace = true
systemd-journal-logger.workspace = true
sd-notify.workspace = true
virtual-serialport = "0.1"
serialport = "4.8.1"
